"""make content in Roadmap model JSONB

Revision ID: 0d1ad0c76ce6
Revises: 37cf2d0b1bf0
Create Date: 2026-06-22 16:55:05.488967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d1ad0c76ce6'
down_revision: Union[str, Sequence[str], None] = '37cf2d0b1bf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "roadmaps",
        "content",
        existing_type=sa.TEXT(),
        type_=postgresql.JSONB(),
        existing_nullable=False,
        postgresql_using="content::jsonb",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roadmaps', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
