"""create roadmaps table

Revision ID: 37cf2d0b1bf0
Revises: 3d1e5c9ffdbe
Create Date: 2026-06-22 15:59:23.019952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37cf2d0b1bf0'
down_revision: Union[str, Sequence[str], None] = '3d1e5c9ffdbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmaps', sa.Column('analysis_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_roadmaps_user_id'), table_name='roadmaps')
    op.create_foreign_key(None, 'roadmaps', 'analyses', ['analysis_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roadmaps', type_='foreignkey')
    op.create_index(op.f('ix_roadmaps_user_id'), 'roadmaps', ['user_id'], unique=False)
    op.drop_column('roadmaps', 'analysis_id')
    # ### end Alembic commands ###
