"""add interview experiences table

Revision ID: aa5a79badf4c
Revises: a15954710274
Create Date: 2026-06-25 01:38:44.440461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa5a79badf4c'
down_revision: Union[str, Sequence[str], None] = 'a15954710274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('interview_type', sa.String(), nullable=False),
    sa.Column('interview_date', sa.Date(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('questions_asked', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('experience', sa.Text(), nullable=False),
    sa.Column('lessons_learned', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_experiences_id'), 'interview_experiences', ['id'], unique=False)
    op.create_index(op.f('ix_interview_experiences_user_id'), 'interview_experiences', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_experiences_user_id'), table_name='interview_experiences')
    op.drop_index(op.f('ix_interview_experiences_id'), table_name='interview_experiences')
    op.drop_table('interview_experiences')
    # ### end Alembic commands ###
